version: "3.9"

services:
  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    env_file:
      - .env_frontend
    volumes:
      - app-data:/data
    network_mode: host
    restart: always

  backend:
    build:
      context: ./Backend
    container_name: backend
    env_file:
      - .env_backend
    volumes:
      - app-data:/data
    network_mode: host
    restart: always

  mediamtx:
    build:
      context: ./MediaMTX
    container_name: mediamtx
    volumes:
      - app-data:/data
    network_mode: host
    restart: always

volumes:
  app-data:
    driver: local
